//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Studenta.
        /// </summary>
        internal static string Add_Student {
            get {
                return ResourceManager.GetString("Add Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da zelite da obrisete ovaj predmet?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_this_Subject_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete this Subject?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosecna ocena.
        /// </summary>
        internal static string AVERAGE {
            get {
                return ResourceManager.GetString("AVERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rodjena*.
        /// </summary>
        internal static string Birthdate_ {
            get {
                return ResourceManager.GetString("Birthdate*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katedra.
        /// </summary>
        internal static string Chair {
            get {
                return ResourceManager.GetString("Chair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katedre.
        /// </summary>
        internal static string Chairs {
            get {
                return ResourceManager.GetString("Chairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi drugi predmet.
        /// </summary>
        internal static string Choose_another_subject {
            get {
                return ResourceManager.GetString("Choose another subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra predmeta.
        /// </summary>
        internal static string CODE {
            get {
                return ResourceManager.GetString("CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra predmeta*.
        /// </summary>
        internal static string Code_ {
            get {
                return ResourceManager.GetString("Code*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna godina studija*.
        /// </summary>
        internal static string Current_Year_ {
            get {
                return ResourceManager.GetString("Current Year*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrisi.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email*.
        /// </summary>
        internal static string Email_ {
            get {
                return ResourceManager.GetString("Email*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espb bodovi.
        /// </summary>
        internal static string ESPB {
            get {
                return ResourceManager.GetString("ESPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESPB*.
        /// </summary>
        internal static string ESPB_ {
            get {
                return ResourceManager.GetString("ESPB*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izlaz.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fajl.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks.
        /// </summary>
        internal static string INDEX {
            get {
                return ResourceManager.GetString("INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks*.
        /// </summary>
        internal static string Index_ {
            get {
                return ResourceManager.GetString("Index*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacija.
        /// </summary>
        internal static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacin finansiranja*.
        /// </summary>
        internal static string Method_of_financing_ {
            get {
                return ResourceManager.GetString("Method of financing*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv*.
        /// </summary>
        internal static string Name_ {
            get {
                return ResourceManager.GetString("Name*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona { format: 06******** }.
        /// </summary>
        internal static string Phonenumber___format__06__________ {
            get {
                return ResourceManager.GetString("Phonenumber { format: 06******** }", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor.
        /// </summary>
        internal static string Professor {
            get {
                return ResourceManager.GetString("Professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor*.
        /// </summary>
        internal static string Professor_ {
            get {
                return ResourceManager.GetString("Professor*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesori.
        /// </summary>
        internal static string Professors {
            get {
                return ResourceManager.GetString("Professors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacuvaj.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestar.
        /// </summary>
        internal static string SEMESTER {
            get {
                return ResourceManager.GetString("SEMESTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestar(Letnji ili Zimski)*.
        /// </summary>
        internal static string Semester_Summer_or_Winter__ {
            get {
                return ResourceManager.GetString("Semester(Summer or Winter)*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        internal static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status studenta.
        /// </summary>
        internal static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentska sluzba.
        /// </summary>
        internal static string Student_services {
            get {
                return ResourceManager.GetString("Student services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti koji slusaju oba predmeta.
        /// </summary>
        internal static string Students_listening_both_subjects {
            get {
                return ResourceManager.GetString("Students listening both subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti koji su polozili samo jedan predmet.
        /// </summary>
        internal static string Students_that_passed_just_first_subject {
            get {
                return ResourceManager.GetString("Students that passed just first subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmet.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmeti.
        /// </summary>
        internal static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string SURNAME {
            get {
                return ResourceManager.GetString("SURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime*.
        /// </summary>
        internal static string Surname_ {
            get {
                return ResourceManager.GetString("Surname*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvanje.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skolska godina.
        /// </summary>
        internal static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina*.
        /// </summary>
        internal static string Year_ {
            get {
                return ResourceManager.GetString("Year*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina upisa*.
        /// </summary>
        internal static string Year_of_enrollment_ {
            get {
                return ResourceManager.GetString("Year of enrollment*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina pohadjanja.
        /// </summary>
        internal static string YEAR_OF_STUDY {
            get {
                return ResourceManager.GetString("YEAR OF STUDY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
